/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DesignRouteImport } from './routes/design'
import { Route as SpikeDataRouteImport } from './routes/spike/data'
import { Route as SpikeElevationRouteImport } from './routes/spike/elevation'
import { Route as SpikeSceneRouteImport } from './routes/spike/scene'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const SpikeDataRoute = SpikeDataRouteImport.update({
  id: '/spike/data',
  path: '/spike/data',
  getParentRoute: () => rootRouteImport,
} as any)
const SpikeElevationRoute = SpikeElevationRouteImport.update({
  id: '/spike/elevation',
  path: '/spike/elevation',
  getParentRoute: () => rootRouteImport,
} as any)
const SpikeSceneRoute = SpikeSceneRouteImport.update({
  id: '/spike/scene',
  path: '/spike/scene',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/design': typeof DesignRoute
  '/spike/data': typeof SpikeDataRoute
  '/spike/elevation': typeof SpikeElevationRoute
  '/spike/scene': typeof SpikeSceneRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/design': typeof DesignRoute
  '/spike/data': typeof SpikeDataRoute
  '/spike/elevation': typeof SpikeElevationRoute
  '/spike/scene': typeof SpikeSceneRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/design': typeof DesignRoute
  '/spike/data': typeof SpikeDataRoute
  '/spike/elevation': typeof SpikeElevationRoute
  '/spike/scene': typeof SpikeSceneRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/design' | '/spike/data' | '/spike/elevation' | '/spike/scene'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/design' | '/spike/data' | '/spike/elevation' | '/spike/scene'
  id:
    | '__root__'
    | '/'
    | '/design'
    | '/spike/data'
    | '/spike/elevation'
    | '/spike/scene'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DesignRoute: typeof DesignRoute
  SpikeDataRoute: typeof SpikeDataRoute
  SpikeElevationRoute: typeof SpikeElevationRoute
  SpikeSceneRoute: typeof SpikeSceneRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spike/data': {
      id: '/spike/data'
      path: '/spike/data'
      fullPath: '/spike/data'
      preLoaderRoute: typeof SpikeDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spike/elevation': {
      id: '/spike/elevation'
      path: '/spike/elevation'
      fullPath: '/spike/elevation'
      preLoaderRoute: typeof SpikeElevationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spike/scene': {
      id: '/spike/scene'
      path: '/spike/scene'
      fullPath: '/spike/scene'
      preLoaderRoute: typeof SpikeSceneRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DesignRoute: DesignRoute,
  SpikeDataRoute: SpikeDataRoute,
  SpikeElevationRoute: SpikeElevationRoute,
  SpikeSceneRoute: SpikeSceneRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
